baseURL = "http://danssoftwareengineeringhandbook.com"
languageCode = "en-us"
title = "Dan's Software Engineering Handbook"
theme = "geekdoc"
googleAnalytics = "G-Y0GC5Z5RJL"

pluralizeListTitles = false
publishDir = "docs"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
    [markup.goldmark.renderer]
        # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4

[params]
    custom_css = ["overrides.css"]
