baseURL = "http://danssoftwareengineeringhandbook.com"
#baseURL = "http://localhost"
languageCode = "en-us"
title = "Dan's Software Engineering Handbook"
theme = "geekdoc"

pluralizeListTitles = false
publishDir = "docs"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
    [markup.goldmark.renderer]
        # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9

[params]
    custom_css = ["overrides.css"]
